print("welcomr to calvert hall")
name = input("what is your name?")
gradyear = input("what year do you graduate?")
standing = input("what is your class standing?")
email = input("what is your email")
print(f"my name is {name}, my gradyear is {gradyear}, my stand is {standing}, my email is {email}")
x = input("What is num1: ")
y = input("what is num2: ")
z = x + y
print(z)